services:
  panetone:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:5264"
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_DB=database
      - DB_USER=sa
      - DB_PASS=821hs91ukd_uwq&1*9j
    networks:
      - backend
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=821hs91ukd_uwq&1*9j
    networks:
      - backend
networks:
  backend:

    